name: CI

on:
  push:
    branches:
      - feat/github-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        yarn install
        yarn build
      env:
        key:
          REACT_APP_API_SERVER: ${{ secrets.REACT_APP_API_SERVER }}
          REACT_APP_STADIA_MAP_API_KEY: ${{ secrets.REACT_APP_STADIA_MAP_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
